## 기본 역량 문제 풀이 20문제(프로그래머스 10 + pyalgo 10)

In [ ]:
def solution(data):
    return

solution()

In [ ]:
# 코딩 인터뷰 완전분석
# 듣기
# 예제
# 무식하게 풀기(V)
# 최적화
# 검토하기
# 구현하기
# 테스트

## 짝수, 홀수 찾기
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120824

In [ ]:
def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]
    print(홀수, 짝수)
    return data

solution([1, 2, 3, 4, 5])

In [ ]:
def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]
    # print(홀수, 짝수)
    return [sum(짝수), sum(홀수)]

In [ ]:
def solution(num_list):
    answer = [0, 0]
    for i in num_list:
        answer[i % 2] += 1
    return answer

In [ ]:
# 좋은 풀이는 아닙니다.
# data의 가변 최대치를 봅니다.
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    return [sum(짝수), len(data) - sum(짝수)] # sum이 순회합니다.

## 머쓱이보다 키 큰 사람
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120585

In [ ]:
def solution(array, height):
    pass

solution([149, 180, 192, 170], 167)

In [ ]:
# 이렇게 언패킹 해서 사용할 수 있는 것들은 언패킹!
# 가독성이 좋아진다!
def solution(data):
    array, height = data
    pass

solution([[149, 180, 192, 170], 167])

In [ ]:
def solution(array, height):
    count = 0
    for i in array:
        if i > height:
            count += 1
    return count

In [ ]:
# filter는 len가 없다
def solution(array, height):
    return list(filter(lambda x: x> height, array))

solution([149, 180, 192, 170], 167)
# 왜 filter에는 len이 없을까?
# filter는 순회 돌기 전까지 실행이 되지 않은 함수
# for와 같이 순회를 돌아야 그제서야 각 원소 별로 접근하기 때문
# 주문만 하고 아직 제조되지 않은 커피
# 커피를 달라고 소리쳐야(순회, 형변환) 그때야 제조가 됨

In [1]:
def solution(array, height):
    return sum(map(lambda x: x > height, array))

solution([149, 180, 192, 170], 167)

3

In [2]:
def solution(array, height):
    return sum(i > height for i in array)

solution([149, 180, 192, 170], 167)

3

## 숨어있는 숫자의 덧셈
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120851

In [ ]:
# 오답, 그러나 이렇게도 많이 사용한다.
def solution(my_string):
    count = 0
    for i in my_string:
        if i.isdigit():
            count += 1

solution("aAb1B2cC34oOp")

In [ ]:
def solution(my_string):
    result = 0
    for i in my_string:
        if i.isdigit():
            result += int(i)

    return result

solution("aAb1B2cC34oOp")

In [ ]:
# isdigit에 () 가 있고 없고의 차이는 무엇인가요?
def 함수(x):
    return x.isdigit()

def solution(my_string):
    return list(filter(함수, my_string))

solution("aAb1B2cC34oOp")

In [ ]:
# 효율적이진 않지만, 문법 복습차원에서
def solution(my_string):
    return sum(map(int,(filter(str.isdigit, my_string))))

solution("aAb1B2cC34oOp")

In [ ]:
# 효율적이진 않지만, 문법 복습차원에서
def solution(my_string):
    return sum(map(lambda x: int(x) if x.isdigit() else False, my_string))

solution("aAb1B2cC34oOp")

In [ ]:
# r은 raw 날것의 라는 뜻이 있다.
# 실무에서 자주쓰는 용어임
# raw data를 전달해줘 => 가공하지 않은 순수 데이터

r'hello\nworld' # \n 이스케이프 문자

In [8]:
import re

def solution(s):
    return sum(map(int, re.findall(r'[0-9]', s)))

solution('aAb1B2cC34oOp')

10

In [ ]:
import re

def solution(s):
    return sum(map(int, (re.sub(r'[a-zA-Z]', '', s))))

solution('aAb1B2cC34oOp')

## 암호해독
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120892

In [ ]:
def solution(cipher, code):
    return cipher[code-1::code]

solution("dfjardstddetckdaccccdegk", 4)

In [ ]:
def solution(cipher, code):
    count = 1
    for i in cipher:
        if count == code:
            print(i)
            count = 0
        count += 1

solution("dfjardstddetckdaccccdegk", 4)

In [ ]:
def solution(cipher, code):
    count = 1
    for i, j in enumerate(cipher, 1):
        if i % code == 0:
            print(j)

solution("dfjardstddetckdaccccdegk", 4)

## 369게임
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120891

In [ ]:
def solution(order):
    order = str(order)
    return order.count('3') + order.count('6') + order.count('9')

In [ ]:
import re

def solution(order):
    order = str(order)
    return len(list(re.findall(r'[369]', order)))

## 중복문자 제거
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120888


In [3]:
set("people") # 중복 제거 완료, 그러나 순서를 보장하지 않음!

{'e', 'l', 'o', 'p'}

In [ ]:
def solution(s):
    answer = ''
    for i in s:
        if i not in answer:
            answer += i
    return answer

In [ ]:
def solution(my_string):
    return ''.join(dict.fromkeys(my_string))

solution('people')

## A로 B 만들기
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120886

In [ ]:
import collections


# collections.Counter("olleh") == collections.Counter("hello")
# collections.Counter("olleh") == collections.Counter("hhhhhhhhhello")
collections.Counter("olleh")

In [ ]:
def solution(before, after):
    a = list(after)
    for i in before:
        if i in a:
            a.remove(i)
        else:
            return 0
    if a:
        return 0
    return 1

solution("olleh", "hello")

In [ ]:
# if문은 많으면 많을수록 좋다!(예외처리)

In [ ]:
# 회문

# 'hello' => 'elloh' => 'llohe'
# 'hello' => 'ohell' => 'lohel'
# collections.deque를 사용해서 풀면 쉽게 풀림

# 문제1 'hello'를 앞뒤로 이동시켜 'llohe'를 만들 수 있나?
# 'hellohello'

# 문제2 몇칸 이동했나?
# 'hellohello'.index('llohe')

## 저주의 숫자 3
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120871

In [ ]:
# 십진수    3숫자마을
# 1         1
# 2         2
# 3         4
# 4         5
# 5         7
# 6         8
# 7         10
# 8         11
# 9         14
# 10        16

In [ ]:
# [True, True, False]...

In [ ]:
# filter('3이 들어간 숫자 없애기', filter('3의 배수 없애기', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

In [ ]:
list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(100)))[15-1]

In [ ]:
def solution(num):
    return list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(1000)))[num-1]

In [ ]:
solution = lambda n:[i for i in range(10000) if i % 3 != 0 and '3' not in str(i)][n-1]

## 진료 순서 정하기
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120835

In [1]:
# emergency     result
# [3, 76, 24]   [3, 1, 2]

def solution(emergency):
    pass


solution([3, 76, 24] )

In [ ]:
data = ['제주', '경기', '전주'] # ['064', '031', '063']
data2 = {
    '제주': '064',
    '경기': '031',
    '전주': '063'
}

[data2[i] for i in data]

In [ ]:
# 좋은 문제입니다.
emergency = [3, 76, 24]

sorted_emergency = sorted(emergency, reverse=True)
sorted_emergency

# 원하는 결과값 [3, 1, 2]
[sorted_emergency.index(i) + 1 for i in emergency]

In [ ]:
# emergency     result
# [3, 76, 24]   [3, 1, 2]

def solution(emergency):
    sorted_emergency = sorted(emergency, reverse=True)
    return [sorted_emergency.index(i) + 1 for i in emergency]


solution([3, 76, 24])

## 가까운 수
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120890

In [ ]:
# [3, 10, 28, 30, 12] => [17, 10, 8, 10, 8]
# [3, 10, 28, 30, 12] => [(17, 3), (10, 10), (8, 28), (10, 30), (8, 12)]
# 원하는 숫자: 20
# result: 28

array = [3, 10, 28, 30, 12]
n = 20

28 - 20 == 8
12 - 20 == -8

20 - 28 == -8
20 - 12 == 8

sorted(array, key=lambda x:(abs(x-n), x))[0]
sorted(array, key=lambda x:(abs(x-n), n-x))[0] # 팁, n-x이거나 x-n 2개 중에 하나입니다.

## k의 개수

링크: https://school.programmers.co.kr/learn/courses/30/lessons/120887

In [9]:
# i    j    k
# 1    13    1

i = 1
j = 13
k = 1

str(list(range(i, j+1)))
'[1, 2, 3]'.count(',')

2

In [10]:
i = 1
j = 13
k = 1

count = 0
for temp in range(i, j):
    count += str(temp).count(str(k))

count

5

In [ ]:
a = 10
b = 20

# swap

temp = a
a = b
b = temp

# python에서 사용하는 swap

a = 10
b = 20
a, b = b, a
a, b

In [ ]:
def solution(i, j, k):
    return str(list(range(i, j+1))).count(str(k))

## 직접 출제 문제

In [ ]:
# 각 선분이 있는 곳에 총 길이 합을 구하라
# [[0, 5], [3, 5], [7, 10]]

선 = [False] * 10
선

In [ ]:
for i in range(0, 5):
    선[i] = True

선

In [ ]:
for i in range(3, 5):
    선[i] = True

선

In [ ]:
for i in range(7, 10):
    선[i] = True

선

In [ ]:
sum(선)

In [3]:
a = 10;b = 10
a, b

(10, 10)

In [ ]:
# 에라토스테스트의 체 => 소수판별 => 이것을 알고리즘 문제로 내는 것은 저는 반대
소수 = [True] * 120
소수[0] = 소수[1] = False

for i in range(4, 120, 2):
    print(i)

for i in range(6, 120, 3):
    print(i)

# for i in range(4, 120, 4):  # 2의 배수에 속하기에 할 필요가 없음
#     print(i)

# https://nahwasa.com/entry/%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98-%EC%B2%B4-%ED%98%B9%EC%9D%80-%EC%86%8C%EC%88%98%ED%8C%90%EC%A0%95-%EC%8B%9C-%EC%A0%9C%EA%B3%B1%EA%B7%BC-%EA%B9%8C%EC%A7%80%EB%A7%8C-%ED%99%95%EC%9D%B8%ED%95%98%EB%A9%B4-%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

In [ ]:
16

# 곱해지는 각 자연수중 하나는 무조건
# 제곱근과 같거나 작아야하는거니까

# 4 * 4
# 2 * 8

# 2, 3, 4

# 2, 4, 6, 8, 10, 12
# 3, 6, 9, 12
# ---
# 5, 10, 15

In [ ]:
for 소수, 판별 in enumerate(소수):
    if 판별:
        print(소수)

## 행렬 연산

In [6]:
# 행렬의 연산과 같은 것은 np를 사용하시면 쉽고 빠르게 풀 수 있습니다.
import numpy as np

x = np.array([1, 2, 3])
x * 2

array([2, 4, 6])

In [7]:
s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
s = np.array(s)
cols, rows = np.where(s == 7)
cols

(array([1]), array([0]))

In [12]:
# 지뢰찾기
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
np.where(x == 1)

(array([0, 1, 2]), array([1, 1, 3]))

In [13]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

s = 0
for i in x:
    s += i.count(1)

s

3

In [ ]:
# 지뢰찾기
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
np.where(x == 1)

## 연습문제

 ### 게임 밸런스 조절
 링크 : https://100.pyalgo.co.kr/?page=10#

In [ ]:
def solution(data):
    filtered_list = list(filter(lambda x: x[1]+x[2]+x[3]+x[4] >= 350, data))
    sorted_list = sorted([i[0] for i in filtered_list])
    return sorted_list

### 우편 번호 정렬
링크 : https://100.pyalgo.co.kr/?page=12

In [ ]:
def solution(data):
    address, post = data[0], data[1]
    sorted_list = sorted(address, key=lambda x:post[x.split()[1]])
    return sorted_list

### 도서관 책 연도별 정렬
링크 : https://100.pyalgo.co.kr/?page=13#

In [ ]:
def solution(data):
    title, sub_year = data[0], data[1]
    sorted_list = sorted(title, key=lambda x:pub_year[x])
    return sorted_list